# Generated by Django 3.1.1 on 2020-11-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('image_front', models.CharField(max_length=500)),
                ('image_back', models.CharField(max_length=500)),
                ('types', models.ManyToManyField(related_name='pokemons', to='pokedex.PokemonType')),
            ],
        ),
    ]
