# Generated by Django 3.1.1 on 2020-11-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=10)),
                ('counter', models.IntegerField()),
            ],
        ),
    ]
